### ISSUE TITLE
environment variable DATA_FILE_DIRECTORIES

### ISSUE THREAD

**Issue by RabieMan** [LukeTillman/dse-docker#4]
Hi,

First, Thanks for your great docker. We are missing one variable that is a great to have:
DATA_FILE_DIRECTORIES

This will enable us to use multi volumes for Cassandra.

Thanks,
Rabie

**Comment by LukeTillman** [comment]
Hi Rabie,

Thanks for the kind words! 

The environment variables used by this image were never meant to cover all the configurations available in the `.yaml` configuration files (or we'd have a TON of them), but rather just to cover the most common ones needed for development environments. If you need to customize the `data_file_directories` setting from the `cassandra.yaml` file, I'd suggest one of these two options:

1. Take advantage of the `/opt/dse/resources` volume and [mount a directory on the host][host-mount-docs] that contains a custom `cassandra.yaml` file that you've created with the settings you need. Your custom file will then be used on startup.
2. Create a new custom docker image of your own (using this one as the base) and modify the `entrypoint.sh` to support changing that configuration at runtime from an environment variable.

If this is for a production setup (where using multiple data directories might be more common), keep in mind that you'll probably also want to expose all of those directories as volumes and mount them to the host (so that the data in them survives if the container is killed).

-L-

[host-mount-docs]: https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume
